name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '45 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been inactive for 60 days. @jbmagination Does this issue still need attention? *This issue will be closed if it goes another 7 days without activity.*'
        stale-pr-message: 'This pull request is stale because it has been inactive for 60 days. @jbmagination Does this pull request still need attention? *This issue will be closed if it goes another 7 days without activity.*'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'