name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '45 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-issue-stale: 30
        days-before-pr-stale: 30
        days-before-close: 7
        days-before-issue-close: 7
        days-before-pr-close: 7
        stale-issue-message: 'This issue is stale because it has been inactive for 30 days. @jbmagination Does this issue still need attention? *This issue will be closed if it goes another 7 days without activity.*'
        stale-pr-message: 'This pull request is stale because it has been inactive for 30 days. @jbmagination Does this pull request still need attention? *This issue will be closed if it goes another 7 days without activity.*'
        close-issue-message: ''
        close-pr-message: ''
        stale-issue-label: 'stale'
        close-issue-label: ''
        close-issue-reason: 'not_planned'
        stale-pr-label: 'stale'
        close-pr-label: ''
        exempt-issue-labels: 'no-stale'
        exempt-pr-labels: 'no-stale'
        only-labels: ''
        only-issue-labels: ''
        only-pr-labels: ''
        any-of-labels: ''
        any-of-issue-labels: ''
        any-of-pr-labels: ''
        operations-per-run: 30
        remove-stale-when-updated: true
        remove-issue-stale-when-updated: true
        remove-pr-stale-when-updated: true
        labels-to-add-when-unstale: ''
        labels-to-remove-when-stale: ''
        labels-to-remove-when-unstale: ''
        debug-only: false
        ascending: true
        start-date: ''
        delete-branch: false
        exempt-milestones: ''
        exempt-issue-milestones: ''
        exempt-pr-milestones: ''
        exempt-all-milestones: true
        exempt-all-issue-milestones: true
        exempt-all-pr-milestones: true
        exempt-assignees: ''
        exempt-issue-assignees: ''
        exempt-pr-assignees: ''
        exempt-all-assignees: false
        exempt-all-issue-assignees: false
        exempt-all-pr-assignees: false
        exempt-draft-pr: true
        enable-statistics: false
        ignore-updates: false
        ignore-issue-updates: false
        ignore-pr-updates: false
        include-only-assigned: false